#!/usr/bin/env node
var db = require('../lib/database');

module.exports = (data) => {
  db.fn('check', data.connection, 'stats', {coin: data.name}).then((exists) =>{
    if (exists == false) {
      console.log('no stats entry found, creating now..');
        db.fn('create', data.connection, 'stats', {coin: data.name}).then(()=>{});
    } else {}
  });
  db.fn('check', data.connection, 'richlist', {coin: data.name}).then((exists)=>{
    if (exists == false) {
      console.log('no richlist entry found, creating now..');
        db.fn('create', data.connection, 'richlist', {coin: data.name}).then(() =>{});
    }
  });
}

